### ISSUE TITLE
bean: Go live checklist

### ISSUE THREAD

**Issue by nizarmah** [whatis277/harvest#112]
We're getting closer to finishing bean and pushing it live

Here's what's left

- [x] Add email client 
- [x] Add user login handler
- [x] Add session management
- [x] Add csrf protection
- [x] Add payment (BuyMeACoffee or Stripe)
- [x] Add a reverse proxy (rate limits, timeouts, logging, health checks)
- [x] Improve go web app (contexts, error handling)
- [x] Deploy to production

**Comment by nizarmah** [comment]
Regarding email sending, I will go with Postmark.

SendGrid is a great option at 100 emails per day. 
Postmark is a good option at 100 emails per month.

But based on readings online, I found myself leaning towards Postmark.

**Comment by nizarmah** [comment]
The email client was just added in #114. 

The PR focused on the local email client — Mailhog.

The needed setup was also done for Postmark.
This will allow local testing using Postmark when needed.

**Comment by nizarmah** [comment]
The user login handler has been added in #115 and #116.
A couple of improvements to email content should be made as well.

Then, we can move on to session management.

**Comment by nizarmah** [comment]
I ended up resting a couple days the last week. I had trouble with my sleep.
That has been resolved, fortunately. So I managed to continue work on the sessions. 

Session management is officially done. It's spread across A LOT of pull requests.

The primary reason is that I chose to restructure the adapters so they're more context-specific. Then, I added the session management to the `auth` adapter. 

I'm happy with how things are implemented and with the corners cut. It's a good balance.

**Comment by nizarmah** [comment]
After carefully looking into CSRF tokens, somehow I managed to implement sessions in a way that took that into account. 🤷🏼 That was a nice coincidence.

I also noticed that we should be using `__Host-` prefix on the session cookie name though. That adds some more complexity with TLS since we need a secure site (HTTPS). So for now, I'm going to leave it until the "add-production" deployment.

**Comment by nizarmah** [comment]
Looking at the remaining items, things like rate limiting, logging, health checks, and server timeouts can all be added with a Reverse Proxy instead of adding it to the Golang application. 

Accordingly, I reduced their priority and prioritized adding payments.

**Comment by nizarmah** [comment]
Okay, we officially have payments. They're called "memberships" in the code. 
It was implemented across multiple pull requests, aligning with the previous message's approach.

It was also given a feature flag to allow enabling/disabling it locally.

**Comment by nizarmah** [comment]
I considered NGINX and Caddy as a reverse proxy.
The ease of use with Caddy was just next level.

So, I'm going with that. Hopefully it's not a bad choice.

**Comment by nizarmah** [comment]
We officially have a reverse proxy. We're using NGINX.

The reverse proxy doesn't healthcheck apps because we don't have NGINX Plus.
The health checks were added to the docker-compose for everything.

Next up, we need to make some final improvements to the go web app, primarily in handling contexts and errors.

**Comment by nizarmah** [comment]
After a day of proper research, the context is being passed down.
It was handled in a chain of pull requests.

I'm still not sure about the context usage in the integration tests.
But it's not an issue right now. It works... 

The error handling is next, but it's going to require some deep research. 
I still have no idea how to address it.

We should also discuss redirecting based on the error?
It might be a bad idea or a good one. I guess we'll find out.

**Comment by nizarmah** [comment]
Forgot to post an update on the improvements with context and error handling.

The code changes were huge, but it's a noticeable improvement. We support logging nicely now.

**Comment by nizarmah** [comment]
This was the first live project in a while. Cheers! 🥳
